/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sokoban.gui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 * A classe JogoEditor representa a janela de jogo dos puzzles editados pelo utilizador.
 * Permite ao jogador jogar um nível personalizado.
 * 
 * @author Tiago Paiva
 */
public class JogoEditor extends javax.swing.JFrame implements Runnable {

    //Tempo
    private Thread t;
    private long ini;
    /**
     * Creates new form JogoEditor
     */
    public JogoEditor() {
        initComponents();
        
        t = new Thread(this);
        ini = System.currentTimeMillis();
        t.start();
    }
    
    /**
     * Atualiza os parâmetros exibidos na interface do jogo.
     */
    public void parametros() {
        //Contagem dos passos
        passosLabel.setText("Passos : " + sokobanPlayEditor2.getPassos());
        //Contagem de caixas arrastadas
        empurroesLabel.setText("Empurrões : " + sokobanPlayEditor2.getEmpurroes());
        if (sokobanPlayEditor2.isComplete()){
            // Exibir uma caixa de diálogo de parabéns
            JOptionPane.showMessageDialog(null, "Parabéns! Concluíste o jogo!", "Jogo Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sokobanPlayEditor1 = new sokoban.SokobanPlayEditor();
        upPanel = new javax.swing.JPanel();
        downPanel = new javax.swing.JPanel();
        btnLoadPuzzle = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        modojogoLabel = new javax.swing.JLabel();
        passosLabel = new javax.swing.JLabel();
        btnTimer = new javax.swing.JLabel();
        empurroesLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        sokobanPlayEditor2 = new sokoban.SokobanPlayEditor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sokobaan Editor");
        setMinimumSize(new java.awt.Dimension(808, 586));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        upPanel.setBackground(new java.awt.Color(97, 153, 180));
        upPanel.setFocusable(false);
        upPanel.setPreferredSize(new java.awt.Dimension(100, 75));

        javax.swing.GroupLayout upPanelLayout = new javax.swing.GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        upPanelLayout.setVerticalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        getContentPane().add(upPanel, java.awt.BorderLayout.LINE_START);

        downPanel.setBackground(new java.awt.Color(97, 153, 180));
        downPanel.setFocusable(false);
        downPanel.setPreferredSize(new java.awt.Dimension(808, 100));
        downPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                downPanelKeyPressed(evt);
            }
        });

        btnLoadPuzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnLoad.png"))); // NOI18N
        btnLoadPuzzle.setBorderPainted(false);
        btnLoadPuzzle.setContentAreaFilled(false);
        btnLoadPuzzle.setFocusable(false);
        btnLoadPuzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPuzzleActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(97, 153, 180));
        btnVoltar.setForeground(new java.awt.Color(97, 153, 180));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnReturn.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setFocusable(false);
        btnVoltar.setPreferredSize(new java.awt.Dimension(32, 32));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRestart.setBackground(new java.awt.Color(97, 153, 180));
        btnRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnRestart.png"))); // NOI18N
        btnRestart.setBorderPainted(false);
        btnRestart.setContentAreaFilled(false);
        btnRestart.setFocusable(false);
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        btnUndo.setBackground(new java.awt.Color(97, 153, 180));
        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnUndo.png"))); // NOI18N
        btnUndo.setBorderPainted(false);
        btnUndo.setContentAreaFilled(false);
        btnUndo.setFocusable(false);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnSetting.setBackground(new java.awt.Color(97, 153, 180));
        btnSetting.setForeground(new java.awt.Color(97, 153, 180));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnSetting.png"))); // NOI18N
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setFocusable(false);

        btnRedo.setBackground(new java.awt.Color(97, 153, 180));
        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/resource/btn/btnRedo.png"))); // NOI18N
        btnRedo.setBorderPainted(false);
        btnRedo.setContentAreaFilled(false);
        btnRedo.setFocusable(false);
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(downPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnLoadPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnLoadPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(downPanel, java.awt.BorderLayout.PAGE_START);

        rightPanel.setBackground(new java.awt.Color(97, 153, 180));
        rightPanel.setFocusable(false);
        rightPanel.setPreferredSize(new java.awt.Dimension(100, 75));

        modojogoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modojogoLabel.setText("Modo : Editor");
        modojogoLabel.setFocusable(false);

        passosLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passosLabel.setText("Passos : 0");
        passosLabel.setFocusable(false);

        btnTimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimer.setText("Tempo : ");
        btnTimer.setFocusable(false);

        empurroesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empurroesLabel.setText("Empurrões : 0 ");
        empurroesLabel.setFocusable(false);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(modojogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btnTimer)
                .addGap(45, 45, 45)
                .addComponent(passosLabel)
                .addGap(32, 32, 32)
                .addComponent(empurroesLabel)
                .addGap(25, 25, 25))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimer)
                    .addComponent(passosLabel)
                    .addComponent(empurroesLabel)
                    .addComponent(modojogoLabel))
                .addContainerGap())
        );

        getContentPane().add(rightPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setBackground(new java.awt.Color(97, 153, 180));
        leftPanel.setFocusable(false);
        leftPanel.setPreferredSize(new java.awt.Dimension(100, 10));
        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_END);
        getContentPane().add(sokobanPlayEditor2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_downPanelKeyPressed

    }//GEN-LAST:event_downPanelKeyPressed

    private void btnLoadPuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPuzzleActionPerformed
        // Carregar jogo
        String mapa = sokobanPlayEditor2.loadFromFile();
        sokobanPlayEditor2.setPuzzle(mapa);
        sokobanPlayEditor2.repaint();
    }//GEN-LAST:event_btnLoadPuzzleActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // Teclas: 
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            sokobanPlayEditor2.movePlayer(-1, 0, 1);
            parametros();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            sokobanPlayEditor2.movePlayer(1, 0, 1);
            parametros();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            sokobanPlayEditor2.movePlayer(0, -1, 1);
            parametros();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            sokobanPlayEditor2.movePlayer(0, 1, 1);
            parametros();
        }
    }//GEN-LAST:event_formKeyPressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Botão voltar ao menu universe:
        EditorPuzzle editor = new EditorPuzzle();
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        // Botão restart
        sokobanPlayEditor2.apagarPuzzle();
        //sokobanPlayEditor2.setPuzzle(mapa);
        sokobanPlayEditor2.restartStatistics();
        passosLabel.setText("Passos: " + sokobanPlayEditor2.getPassos());
        empurroesLabel.setText("Empurrões : " + sokobanPlayEditor2.getEmpurroes());
        ini = System.currentTimeMillis();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // Botão Undo:
        //sokobanPlayEditor2.undo();
        passosLabel.setText("Passos: " + sokobanPlayEditor2.getPassos());
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        // Botão redo:
        sokobanPlayEditor2.redo();
        passosLabel.setText("Passos : " + sokobanPlayEditor2.getPassos());
    }//GEN-LAST:event_btnRedoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadPuzzle;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel btnTimer;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel empurroesLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel modojogoLabel;
    private javax.swing.JLabel passosLabel;
    private javax.swing.JPanel rightPanel;
    private sokoban.SokobanPlayEditor sokobanPlayEditor1;
    private sokoban.SokobanPlayEditor sokobanPlayEditor2;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
